name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Fix husky permissions
        run: chmod +x node_modules/.bin/husky || true
      - run: npm install
      - run: npm run buil
      - name: Install dependencies
        run: cd my-pwa && npm install
      
      - name: Build
        run: cd my-pwa && npm run build
